version: '3.8'

services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ${HOME}:/host-home
    environment:
      - PORT=3001
      - HOST_HOME=/host-home
      - USER_HOME=${HOME}
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
